config/routes.rb
Rails.application.routes.draw do
	root :to => 'application#home'
  resources :posts
  resources :attachments
  resources :pictures
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attachment.rb
class Attachment < ApplicationRecord
  belongs_to :attachable, polymorphic: true, optional: true
  has_attached_file :file

  validates_attachment :file,
  	:presence => true,
    :content_type => { :content_type => ["application/pdf","application/vnd.ms-excel",     
             "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
             "application/msword", 
             "application/vnd.openxmlformats-officedocument.wordprocessingml.document", 
             "text/plain"] },
    :size => { :in => 0..5.megabytes }
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :imageable, polymorphic: true, optional: true

  has_attached_file :image, 
  					:styles => { :large => "500x300#", :medium => "300x300>", :thumb => "100x100>" }, 
  					default_url: "/images/:style/missing.png"
  
  validates_attachment :image, :presence => true,
  					   :content_type => { :content_type => /\Aimage\/.*\z/ },
                       :size => { :in => 0..5.megabytes }
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :attachments, as: :attachable, dependent: :destroy
	has_many :pictures, as: :imageable, dependent: :destroy
	validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def home
  	render template: "pages/home"
  end
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  before_action :set_attachment, only: [:show, :edit, :update, :destroy]

  # GET /attachments
  # GET /attachments.json
  def index
    @attachments = Attachment.all
  end

  # GET /attachments/1
  # GET /attachments/1.json
  def show
  end

  # GET /attachments/new
  def new
    @attachment = Attachment.new
  end

  # GET /attachments/1/edit
  def edit
  end

  # POST /attachments
  # POST /attachments.json
  def create
    @attachment = Attachment.new(attachment_params)

    respond_to do |format|
      if @attachment.save
        format.html { redirect_to @attachment, notice: 'Attachment was successfully created.' }
        format.json { render :show, status: :created, location: @attachment }
      else
        format.html { render :new }
        format.json { render json: @attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attachments/1
  # PATCH/PUT /attachments/1.json
  def update
    respond_to do |format|
      if @attachment.update(attachment_params)
        format.html { redirect_to @attachment, notice: 'Attachment was successfully updated.' }
        format.json { render :show, status: :ok, location: @attachment }
      else
        format.html { render :edit }
        format.json { render json: @attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attachments/1
  # DELETE /attachments/1.json
  def destroy
    @attachment.destroy
    respond_to do |format|
      format.html { redirect_to attachments_url, notice: 'Attachment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attachment
      @attachment = Attachment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attachment_params
      params.require(:attachment).permit(:file)
    end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]
  before_action :set_s3_direct_post, only: [:new, :edit, :create, :update]

  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.all
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
  end

  # GET /pictures/new
  def new
    @picture = Picture.new
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(picture_params)

    respond_to do |format|
      if @picture.save
        format.html { redirect_to @picture, notice: 'Picture was successfully created.' }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url, notice: 'Picture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    def set_s3_direct_post
      @s3_direct_post = S3_BUCKET.presigned_post(key: "uploads/#{SecureRandom.uuid}/${filename}", success_action_status: '201', acl: 'public-read')
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_params
      params.require(:picture).permit(:image)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    @pictures = Picture.all
    @attachments = Attachment.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
    @picture = Picture.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        if params[:images]
          params[:images].each { |image|
            @post.pictures.create(image: image)
          }
        end

        if params[:files]
          params[:files].each { |file|
            @post.attachments.create(file: file)
          }
        end

        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def destroy_all
    Post.delete_all
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/attachments/_form.html.erb
<%= form_for(attachment) do |f| %>
  <% if attachment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(attachment.errors.count, "error") %> prohibited this attachment from being saved:</h2>

      <ul>
      <% attachment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :file %>
    <%= f.file_field :file %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/attachments/edit.html.erb
<h1>Editing Attachment</h1>

<%= render 'form', attachment: @attachment %>

<%= link_to 'Show', @attachment %> |
<%= link_to 'Back', attachments_path %>

app/views/attachments/index.html.erb
<div class="left jumbotron">
<p id="notice"><%= notice %></p>

<h1>Attachments</h1>

<table>
  <thead>
    <tr>
    </tr>
  </thead>

  <tbody>
    <% @attachments.each do |attachment| %>
      <div class="panel panel-default">
        <div class="panel-body">  
          <%= attachment.file_file_name %><br><br>
          <%= link_to "Show", attachment, class: "btn btn-primary btn-xs", role: "button" %>
          <%= link_to "Destroy", attachment, method: :delete, data: { confirm: 'Are you sure?' }, 
                  class: "btn btn-default btn-xs", role: "button" %>
        </div>
      </div>
    <% end %>
  </tbody>
</table>
<br>
</div>

app/views/attachments/new.html.erb
<h1>New Attachment</h1>

<%= render 'form', attachment: @attachment %>

<%= link_to 'Back', '/#' %>

app/views/attachments/show.html.erb
<div class="left jumbotron">
<p id="notice"><%= notice %></p>


<p>
  <strong>Attachable type:</strong>
  <%= @attachment.file_file_name %>
</p>
<p>
	<strong>Post: </strong>
		<a href="<%=  polymorphic_path(@attachment.attachable) %>"><%= @attachment.attachable.try(&:title) %></a>
</p>

<%= link_to 'Back', attachments_path %>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="https://gizelles3.herokuapp.com/">Paperclip-S3 Demo</a>
    by <a href="https://bitbucket.org/mademoizelle/">Gizelle Peras</a>
  </small>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-nav navbar-fixed-top">
  <div class="container">
    <%= link_to "Paperclip-S3 Demo", '#', id: "logo" %>
    <nav>
    <ul class="nav nav-tabs navbar-custom">
        <li><%= link_to "Home",   '/#' %></li>
        <li><%= link_to "Posts",   posts_path %></li>
        <li><%= link_to "All Photos",   pictures_path %></li>
        <li><%= link_to "All Files",   attachments_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>S3</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
    <%= render 'layouts/shim' %>
  </head>
  <body>
  	<%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="left jumbotron">
  <h1>Welcome to the Paperclip-S3 Demo</h2>

    Paperclip let's you add attachments such as photos as well as files. <br>
    S3 is where the photos and files are being uploaded. <br><br>
    You can check progress bar in pictures/new. It is a direct upload to S3, <br>
    but I wasn't able to get the object from S3, to pass it to the controller.<br><br>

  <%= link_to "Create a Post", 'posts/new', class: "btn btn-lg btn-primary" %>

</div>


<%= link_to image_tag("rails.png", alt: "Rails logo"), 'https://www.ruby-lang.org/en/' %>

app/views/pictures/_form.html.erb
<%= form_for(@picture, html: { multipart: true, class: 'directUpload', data: { 'form-data' => (@s3_direct_post.fields), 'url' => @s3_direct_post.url, 'host' => URI.parse(@s3_direct_post.url).host } }) do |f| %>
  <% if picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% picture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image, multiple: true %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/pictures/edit.html.erb
<h1>Editing Picture</h1>

<%= render 'form', picture: @picture %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/index.html.erb
<div class="left jumbotron">
<p id="notice"><%= notice %></p>

<h1>Pictures</h1>

<table>
  <thead>
    <tr>
    </tr>
  </thead>

  <tbody>
    <div class="container">
      <div class='row'>
        <% @pictures.each do |picture| %>
          <div class='col-sm6 col-md-4 row-eq-height'>
            <div class="thumbnail">
              <div class="img-wrapper">
                <%= image_tag(picture.image.url, class: "img-responsive") %><br>
                Post: <%= picture.imageable.try(&:title) %><br><br>
                <%= link_to "Show", picture, class: "btn btn-primary btn-xs", role: "button" %>
                <%= link_to "Destroy", picture, method: :delete, data: { confirm: 'Are you sure?' }, 
                            class: "btn btn-default btn-xs", role: "button" %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </tbody>
</table>
</div>

app/views/pictures/new.html.erb
<h1>New Picture</h1>

<%= render 'form', picture: @picture %>

<%= link_to 'Back', '/#' %>

app/views/pictures/show.html.erb
<div class="left jumbotron">
<p id="notice"><%= notice %></p>

<p>
	<%= image_tag @picture.image.url %>
</p>
<p>
	<strong>Post: </strong>
		<a href="<%=  polymorphic_path(@picture.imageable) %>"><%= @picture.imageable.try(&:title) %></a>
</p>

<%= link_to 'Back', pictures_path %>
</div>

app/views/posts/_form.html.erb
<!-- app/views/galleries/_form.html.erb -->
<%= form_for @post, :html => { :class => 'form-horizontal', multipart: true } do |f| %>

  <div class="form-group">
    <%= f.label :title, :class => 'control-label' %>
    <%= f.text_field :title, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :content, :class => 'control-label' %>
    <%= f.text_area :content, rows: 5, :class => 'form-control' %>
  </div>
  <div class="control-group">
    <%= f.label :pictures, :class => 'control-label' %>
    <%= file_field_tag "images[]", type: :file, multiple: true %>
  </div>
  <div class="control-group">
    <%= f.label :attachments, :class => 'control-label' %>
    <%= file_field_tag "files[]", type: :file, multiple: true %>
  </div>
  <br>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                posts_path, :class => 'btn btn-mini' %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="left jumbotron">
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <div class="row">
      <% @posts.each do |post| %>
        <div class="panel panel-default">
          <div class="panel-body">
            <h4><strong><a href="<%= post_path(post) %>"><%= post.title %></a></strong></h4>
            <% if post.pictures.first %>
              <img src="<%= post.pictures.first.image.url(:medium) %>"/>
            <% else %>
              <img/>
            <% end %>     
            <%= post.content %><br><br>
            <%= link_to 'Edit', edit_post_path(post), class: 'btn btn-default btn-sm' %>
            <%= link_to 'Remove', post, :method => :delete, :data => { :confirm => 'Are you sure?', :remote => true }, class: 'btn btn-default btn-sm remove' %>
          </div>
        </div>
      <% end %>
    </div>
  </tbody>
</table>

<br>

<%= link_to 'Back', '/#' %>
</div>


<hr>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', '/#' %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p>
  <strong>Image</strong>
  <% @post.pictures.each do |picture| %>
  		<%= image_tag picture.image.url %>
  <% end %>
</p>

<p>
  <strong>Attachment:</strong>
  <% @post.attachments.each do |attachment| %>
  		<%= attachment.file_file_name %>
  <% end %>
</p>



<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>